--Q. what is the total revenue generated by male vs female customers
select
gender,
sum(purchase_amount) as revenue
from seventh-league-335114.data_1.customer_behavior
group by gender

--Q.which customers used a discount but still spent more than avg purchase amount?
select
customer_id,
purchase_amount
from seventh-league-335114.data_1.customer_behavior
where discount_applied=True and purchase_amount>= (select avg(purchase_amount) from seventh-league-335114.data_1.customer_behavior )

--Q.which are the top 5 products with the highest avg review rating?
select
item_purchased,
round(avg(review_rating),2) as avg_ratings
from seventh-league-335114.data_1.customer_behavior
group by item_purchased
order by avg_ratings desc
limit 5

--Q.compare the avg purchase amounts between standard and express shipping
select
shipping_type,
round(avg(purchase_amount),2)
from seventh-league-335114.data_1.customer_behavior
where shipping_type in ('Standard','Express')
group by shipping_type

--Q.Do subsribed customers spend more?. compare avg spend and total revenue between subscribers and non subscribers
select
case when subscription_status is True then 'Subscriber' 
     when subscription_status is False then 'Non-Subsciber'
     end as subcription_stats,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_purchase,
sum(purchase_amount) as tot_pruchase
from seventh-league-335114.data_1.customer_behavior
group by subcription_stats
--Q.which 5 products have the highest percentage of purchases with discounts applied.

select
item_purchased,
round(100*sum(case when discount_applied= True then 1 else 0 end )/count(*),2) as discount_rate
from seventh-league-335114.data_1.customer_behavior
group by item_purchased
order by discount_rate desc
limit 5


--Q.segment customers into new,returning,loyal based on their total number of previous purchases and show the count of each segment


with main as
(select
customer_id,
previous_purchases,
case when previous_purchases < 2 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
     else 'Loyal' end as customer_stats
from seventh-league-335114.data_1.customer_behavior
)

select
customer_stats,
count(*)
from main
group by customer_stats


--Q.what are the top 3 most purchased products within each category?

with main as
(select
category,
item_purchased,
count(item_purchased) as no_of_purc,
row_number()over(partition by category order by count(item_purchased) desc) as rnk
from seventh-league-335114.data_1.customer_behavior
group by 1,2
)

select
*
from main
where rnk <=3


--Q.are customers who are repeat buyers (more than 5 previous purchases)also likely to subscribe

select
subscription_status,
count(customer_id) as repeat_buyer
from seventh-league-335114.data_1.customer_behavior
where previous_purchases>5
group by subscription_status


--Q.what is the revenue contribution of each age group

select age_group,
sum(purchase_amount) as total_revenue
from seventh-league-335114.data_1.customer_behavior
group by age_group 
order by total_revenue desc
